name: async_listenable
description: ValueListenable/ValueNotifier for async operations
version: 1.1.0
homepage: https://github.com/s0nerik/async_listenable
repository: https://github.com/s0nerik/async_listenable
topics:
  - reactive
  - ui
  - async
  - state-management

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  fake_async: ^1.3.1

flutter:
