# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Tests Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - name: Test and Collect Coverage
        run: |
          flutter pub get
          flutter analyze
          flutter test --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
            files: ./coverage/lcov.info
            flags: unittests
